### ISSUE TITLE
Es_systems.cfg conflict with gridview

### ISSUE THREAD

**Issue by HerbFargus** [jacobfk20/EmulationStation#1]
carried over from the forum here: https://retropie.org.uk/forum/topic/3121/emulationstation-mod/81

Not sure what the best solution is, we could do an overall grid config in settings.cfg at the expense of the system specific modularity or have some equivalent system specific config that doesn't conflict.

**Comment by jacobfk20** [comment]
The latter can possibly be done straight in systemdata.  It just will only save/load user configurable stuff.

**Comment by jacobfk20** [comment]
I've tested it a couple of times and it seems to be working pretty good.  es_systems.cfg now stays in /etc.

**You can safely delete es_systems.cfg in /.emulationstation**

**Comment by HerbFargus** [comment]
it seems to be segfaulting on my build for some reason

debug log:

```
lvl2:   EmulationStation - v2.0.1a, built Aug 11 2016 - 15:02:50
lvl2:   Creating surface...
lvl2:   Created window successfully.
lvl2:   Checking available OpenGL extensions...
lvl2:    ARB_texture_non_power_of_two: ok
lvl2:   Loading system config file /home/seamus_linux/.emulationstation/es_systems.cfg...
lvl2:   Parsing XML file "/home/seamus_linux/.emulationstation/gamelists/ports/gamelist.xml"...
lvl2:   Parsing XML file "/home/seamus_linux/.emulationstation/gamelists/retropie/gamelist.xml"...
lvl1:   File ""/home/seamus_linux/RetroPie/retropiemenu/audiosettings.rp"" does not exist! Ignoring.
lvl1:   File ""/home/seamus_linux/RetroPie/retropiemenu/raspiconfig.rp"" does not exist! Ignoring.
lvl1:   File ""/home/seamus_linux/RetroPie/retropiemenu/splashscreen.rp"" does not exist! Ignoring.
lvl2:   Parsing XML file "/home/seamus_linux/.emulationstation/gamelists/snes/gamelist.xml"...
Segmentation fault
```

**Comment by jacobfk20** [comment]
Put a copy of es_systems.cfg into .emulationstation.  I don't think it'll fix it, but just want to be sure.

**Comment by HerbFargus** [comment]
still segfaults unfortunately

**Comment by jacobfk20** [comment]
Okay, thanks for trying.  I'll commit in a couple minutes with a possible fix.

**Comment by jacobfk20** [comment]
That should do it.

**Comment by HerbFargus** [comment]
can confirm its resolved :+1:

**Comment by jacobfk20** [comment]
Sweet!  Thanks for the help.
