### ISSUE TITLE
Box Art appearing as White Rectangles

### ISSUE THREAD

**Issue by dudleydes** [jacobfk20/EmulationStation#18]
I am using the gridview EmulationStation binary downloaded from your Google Drive (dated 6 October 2016). Recently box art is failing to load, to be replaced by white rectangles (see image)

![unresolved tiles](https://cloud.githubusercontent.com/assets/8166945/20456661/d982453c-ae72-11e6-956d-d6af170e925e.png)

If I bring up the ES menu, then the letters are replaced by blocks such as [U+258C](http://www.fileformat.info/info/unicode/char/258c/index.htm) (I could not get an image as the program I use, raspipng, returned a `vc_dispmanx_snapshot() failed` error). Restarting ES will resolve the issue but the white rectangles soon begin appear again.

I changed the grid size from 8 by 3 to 6 by 3 but the issue remains.

Here are logs that may help to resolve the issue.

es_log.txt
http://pastebin.com/2r13fYcF

output of `sudo vcdbg reloc`
http://pastebin.com/LhjBtDHt
Line 528 `heap corruption detected` may be relevant.

I am using a Raspberry Pi 2 with no overclocking and default GPU split of 256. I have 12 systems, of which 9 use gridview.

If there is further information you would like then let me know.

**Comment by jacobfk20** [comment]
First of all, thanks for the well documented issue. :)

This is caused from running out of vram.  Gridview should unload all boxart for all games (except the first game) when you switch systems, folders, or back out into system view.  This will keep vram usage low which in return will keep this white rectangle problem from happening.

This could be a problem with the theme you're using.  Did you make that theme?  ES loads in all System Art into vram on load and keeps it there.  Then when you load in a system with grid view it'll blow what little vram that is left.  

I've been wanting to fix this issue for awhile now but can't find a decent solution that doesn't either put restrictions on theme makers or adds some slight slowdowns as ES has to constantly load/unload system art as the user moves around systems.

If it is not a problem can I have a copy of this theme you're using?  I'd like to test on my hardware with my latest build.  

A couple things to test: 
* Enable FPS counter and take note of VRAM usage before opening any systems.  If you're already pushing around 100MBs then the theme art is too high quality.  
* Another thing to note is that when an image is copied to the GPU's ram it will be uncompressed to its raw format, so a 500k image may be 10m in vram.
* If you're the theme maker, try lowering the size of the images 
* Try Lilbud's Material theme.  It uses vary little vram and supports Gridview.  I also use this for most testing.

**Comment by lilbud** [comment]
Just wanted your opinion, any changes you would to see to the Material theme?

**Comment by dudleydes** [comment]
I am using a theme I created based on Carbon, the RetroPie default, where I added a `<view name="grid">` element to enable gridview. Here is a copy of the theme I am using:
[es-theme-carbon-master.zip](https://github.com/jacobfk20/EmulationStation/files/608572/es-theme-carbon-master.zip)


When I turn on FPS in ES, the vram usage is hitting 100mb as it loads box art though it doesn't seem to lower when returning to system view. I did make a number of revisions to the Carbon theme along the way so that may have bloated the vram usage.

The vram used by fonts is 41.94mb which is higher than the 25.17mb used by the vanilla Carbon and Material themes. I did experiment with the `gridtile_text` attribute. When I removed this, text on the gridtile remained - I don't know if this is a bug? In any case, to remove the text, I am using the Adobe Blank font which is using ~6mb of vram. This does not explain the extra 11mb used.

I have lowered the size of the images for the SNES box art and that has seen the vram drop to 84mb. I'm trying to keep images to under 30kb. Is this a good size or should I aim to go lower?

I intend to go back to a fresh copy of the Carbon theme and try to optimise the quality of box art for the other systems. I'll let you know how things go.

**Comment by dudleydes** [comment]
I have taken a fresh copy of the Carbon theme and added gridview support. When I select gridview for SNES, say, the vram used by fonts goes from 20.97mb to 29.36mb. I do not see a similar increase when using the Material theme. 

Here is the latest version of my theme. I would be grateful if you could test and find why the vram for fonts increases.
[es-theme-carbon-master.zip](https://github.com/jacobfk20/EmulationStation/files/610888/es-theme-carbon-master.zip)

With the optimised images, the total vram is maxing out at 80mb. Also, I've noticed that the gridtile text is always present and the best way to remove it text is to make the colour transparent.

**Comment by jacobfk20** [comment]
I've been working on a fairly big update to this mod and I think the increase in font vram may be fixed in the newer builds (I'll test and see)  I will also take some time soon to finally fix the white rectangle problem for good.  I think I found a decent solution to this problem that won't put huge restrictions on themers.  (it may not make it to the next update as it may be a long testing process)

Yes, setting text to transparent in the newest build (which isn't published) will also give some fps increases as well.  Another increase with font vram can also be linked with metadata.  When I do gridtile optimizations here in the next week I will try and get these vram hogs controlled.  My goal is for ES to never use more than 80mb of vram total.

I will also find a way to optimize boxart so you don't have to.  Maybe have ES cache smaller thumbs as well for speed.

Sometime today I will use your carbon theme you uploaded above and see whats going on.  

@lilbud your theme is pretty nice, I love it.  The only thing you need to add is gridsize support for every system.  using:
```
<container name="gridRowsAndColumns"> <size>
<container name="gridRowsAndColumns-small"> <size>
<container name="gridRowsAndColumns-big"> <size>
```
I've created these tags for a couple of systems for my personal use already.  Such as for Snes I did this setup:
```
                <container name="gridRowsAndColumns">
                        <size>4 4</size>
                </container>
                <container name="gridRowsAndColumns-big">
                        <size>3 3</size>
                </container>
                <container name="gridRowsAndColumns-small">
                        <size>5 5</size>
                </container>
```

Unless you already did this and I haven't noticed which is possible.

**Comment by dudleydes** [comment]
Good news about the new update. I look forward to it.

I have lowered the quality of box art, pretty straightforward with ImageMagick, and tested the impact on vram. When ES launches, the total vram used is 56.83mb. Browsing Atari 2600 (72 roms) increases this to 67.59mb and returning to system view to 64.45mb. Repeat for NES (96 roms) 81.00mb, then 71.44mb in system view. Repeat for Megadrive (96 roms) 86.64mb, then 79.22mb. The total vram continues to increase while I browse systems, even if they have loaded already.

I tested with the Material theme and observed similar increments as I browsed through systems. I also observed that the increments seemed to be dependent on the number of tiles in grid view, the larger the array, the larger the increase.

The vram continues to increase past 100mb where the white rectangles become an issue. The vram can be reset by restarting ES or by changing the view mode to Normal, then back to Grid View.

**Comment by jacobfk20** [comment]
Alright, this problem may have been introduced in a recent commit.  I was able to reproduce your problem on the latest build with similar results.  I already know the cause.  Exiting a system isn't clearing boxart from ram because when a system loses focus it no longer updates.  Another problem here is when a system regains focus it will continue the unloading of textures then just reload them right back in. 

The commit that causes this is one of the latest ones.
Also, thanks for taking the time 👍

**Comment by dudleydes** [comment]
Thank you for the update.

I have complied a binary with the fix and everything seems to be working fine. Each time I load gridview, then return to system view, the textures vram will increase by 0.3-0.5mb for each system. I'm assuming this increase is expected because ES is keeping the boxart of the first game for each system in the vram. If I visit the gridview for a system previously visited and then return to system view, then there is no further increase in vram.

I'm not sure what's happening with the fonts vram. It's currently running at 33.55mb and I can't find a way of reducing it. It's not a issue regarding the white rectangles appearing because from testing the new binary, the total vram is maxing out at around 82mb for any system in gridview.

PS. Has `<ninepatch>` been retired in favour of `<image>`? If so, then the documentation in GRIDTHEME.md will need to be updated.

**Comment by jacobfk20** [comment]
No problem, thanks for letting me know.  Also you're correct, ES will keep the first boxart in memory.

Yes, Ninepatch will no longer work as it is incomplete upstream.  I did this for compatibility.
Thanks for reminding me, I'll update GRIDTHEME.md

I haven't looked a whole lot into the font vram spike but I will be doing some house cleaning soon and maybe find something along the way.

**Comment by dudleydes** [comment]
I have added more systems to Gridview and I have not noticed the white rectangles issue since the changes.

I suggest closing this issue and that I open two new issues so that they can be tracked separately. One relates to the font vram and the other to the need to optimise box art to keep vram levels down to avoid the white rectangles appearing. What do you think?

**Comment by jacobfk20** [comment]
That's fine.  It will actually help having everything in their own issue thread.  Well, for me at least.

**Comment by dudleydes** [comment]
Done.
