### ISSUE TITLE
duplicate boxart on latest build

### ISSUE THREAD

**Issue by HerbFargus** [jacobfk20/EmulationStation#3]
On the latest version, every time I play a game it adds another entry of that game to the grid view list. Or if I have 5 games, it will duplicate entries for all 5 games. it resets to just one set when I restart emulationstation

Also the triggers/shoulders dont seem to do anything even when I changed them all to grid view (perhaps for a separate issue)

**Comment by jacobfk20** [comment]
I'll upload a build soon

**Comment by jacobfk20** [comment]
https://drive.google.com/open?id=0ByWG5kDXyr5NM1c4UHdQeWcxMG8

**Comment by HerbFargus** [comment]
can confirm its fixed. you work quick!

**Comment by jacobfk20** [comment]
Thanks :)  I try to dedicate a couple hours a day on this project.
